#ddev-generated
# Usage: `ddev pull dev`
auth_command:
  command: |
    set -eu -o pipefail
    RED='\033[0;31m'
    NC='\033[0m'
    if ! ssh-add -l >/dev/null; then
        echo -e "${RED}Error: SSH agent not active.${NC} Run 'ddev auth ssh' first."
        exit 1
    fi

db_pull_command:
  skip_import: true
  service: web
  command: |
    export PULL_ENV="dev"
    bash ${DDEV_COMPOSER_ROOT:-/var/www/html}/.ddev/providers/pull_script.sh
